# This is a basic workflow to help you get started with Actions

name: copy labels

# Controls when the workflow will run
on:
  push:
      branches:
        - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  grab-repo-list:
    runs-on: ubuntu-latest
    steps:
      - name: grab repos
        run: |
          echo 'repos<<EOF' >> $GITHUB_ENV
          echo -n "{\"repos\":" >> $GITHUB_ENV
          echo -n $(gh repo list ryanhTesting --json nameWithOwner --jq '[.[].nameWithOwner]') >> $GITHUB_ENV
          echo "}" >>$GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

    outputs:
      repos: ${{ env.repos }}

  distribute-labels:
    runs-on: ubuntu-latest
    needs: grab-repo-list
    strategy:
      matrix: ${{ fromJSON(needs.grab-repo-list.outputs.repos) }}
    steps:
      - name: distribution
        run: |
         gh label clone ${{ github.repository_owner }}/default --repo https://github.com/${{ matrix.repos }}
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
