# This is a basic workflow to help you get started with Actions

name: Test Poetry install

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: curl webhook endpoint
        run: curl gitlab-trace-webhook.default.svc
