# This is a basic workflow to help you get started with Actions

name: Test Poetry install

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install:
    runs-on: self-hosted
    steps:
      - name: build alpine python image with poetry install
        run: docker build .
