on:
  workflow_call:
    inputs:
      variable1:
        required: true
        type: string
    secrets:
      secret1:
        required: true


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: variable1
        run: echo ${{ inputs.variable1 }}
      - name: secret1
        run: echo ${{ secrets.secret1 }}
