name: grabbing wiki data on change

on:
  gollum

jobs:
  grab-wiki-data:
    runs-on: ubuntu-latest
    steps:
      - name: checkout wiki
        uses: actions/checkout@v3
        with: 
          repository: ${{github.repository}}.wiki 
      - name: echo pages
        env:
          PAGE_NAME: ${{ toJson(github.event.pages[0].page_name) }}
        run: |
          echo "page=$PAGE_NAME.md" >> $GITHUB_ENV
      - name: testing env
        run: echo ${{ env.page }}

