name: grabbing wiki data on change

on:
  gollum

jobs:
  grab-wiki-data:
    runs-on: ubuntu-latest
    steps:
      - name: checkout wiki
        uses: actions/checkout@v3
        with: 
          repository: ${{github.repository}}.wiki 
          
      - name: echo pages
        env:
          PAGE_NAME: ${{ toJson(github.event.pages[0].page_name) }}
        run: |
          echo "page=${{env.PAGE_NAME}}.md" >> $GITHUB_ENV
          echo "page_name=$PAGE_NAME" >> $GITHUB_ENV
      - name: outputting page
        run: |
          echo 'page_data<<EOF' >> $GITHUB_ENV
          cat ${{ env.page }}  >> $GITHUB_ENV
          echo '' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "Title": ${{ toJson(github.event.pages[0].page_name) }} ,
              "EOD": ${{ toJson(env.page_data) }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.webhook_url}}

